import { createContext, useContext } from 'react';
import DEFAULT_PHOTOS from './defaultPhotos.json';

// A photo is {url, s, fx, fy}: s = zoom (1 = cover-fill), fx/fy = the point
// of the image (0..1 across its width/height) that should sit in the middle of
// the frame. A focal point works for any frame shape, so a position set in the
// studio carries over to the wide desktop banner, a tall phone frame and the
// narrow gallery slats alike. Older photos store x/y instead (offset of the
// image centre from the frame centre, in % of the frame, the Design tool's
// model); those are converted per frame in `placement`.
//
// Lookup order for a slot: Danique's upload (ad-photos) → the photo that was
// dropped into the Design file (defaultPhotos.json, generated by
// `npm run import-photos`) → the slot's built-in src → empty placeholder.

export const PhotosContext = createContext({});

export function resolvePhoto(photos, slotId, fallbackSrc, fallbackFocus) {
  const own = photos && photos[slotId];
  if (own && own.url) return normalizePhoto(own);
  const def = DEFAULT_PHOTOS[slotId];
  if (def && def.url) return normalizePhoto(def);
  if (fallbackSrc) return normalizePhoto({ url: fallbackSrc, ...fallbackFocus });
  return null;
}

export function usePhoto(slotId, fallbackSrc, fallbackFocus) {
  return resolvePhoto(useContext(PhotosContext), slotId, fallbackSrc, fallbackFocus);
}

const clamp01 = (v) => Math.min(1, Math.max(0, v));

export function normalizePhoto(p) {
  const n = (v, d) => (Number.isFinite(v) ? v : d);
  const out = { url: p.url, s: Math.min(4, Math.max(1, n(p.s, 1))) };
  if (Number.isFinite(p.fx) || Number.isFinite(p.fy)) {
    out.fx = clamp01(n(p.fx, 0.5));
    out.fy = clamp01(n(p.fy, 0.5));
  } else {
    out.x = n(p.x, 0);
    out.y = n(p.y, 0);
  }
  return out;
}

// True when the photo is a plain centred cover-fill (no layout maths needed).
export function isPlain(photo) {
  if (photo.s !== 1) return false;
  if ('fx' in photo) return photo.fx === 0.5 && photo.fy === 0.5;
  return !photo.x && !photo.y;
}

// Image size in frame-% for a given image ratio (w/h) and frame ratio (w/h).
export function photoBox(s, imageRatio, frameRatio) {
  return {
    w: s * 100 * Math.max(1, imageRatio / frameRatio),
    h: s * 100 * Math.max(1, frameRatio / imageRatio),
  };
}

// The focal point of a photo for this frame (legacy x/y converted).
export function focusOf(photo, imageRatio, frameRatio) {
  if ('fx' in photo) return { fx: photo.fx, fy: photo.fy };
  const { w, h } = photoBox(photo.s, imageRatio, frameRatio);
  return { fx: clamp01(0.5 - photo.x / w), fy: clamp01(0.5 - photo.y / h) };
}

// Where the image goes in this frame: size and top-left corner in frame-%.
// The focal point is centred as far as possible without showing a gap.
export function placement(photo, imageRatio, frameRatio) {
  const { w, h } = photoBox(photo.s, imageRatio, frameRatio);
  const { fx, fy } = focusOf(photo, imageRatio, frameRatio);
  const left = Math.min(0, Math.max(100 - w, 50 - fx * w));
  const top = Math.min(0, Math.max(100 - h, 50 - fy * h));
  return { w, h, left, top };
}
