import { createContext, useContext } from 'react';
import DEFAULT_PHOTOS from './defaultPhotos.json';

// A photo is {url, s, fx, fy, crop?}: s = zoom (1 = cover-fill), fx/fy = the point
// of the image (0..1 across its width/height) that should sit in the middle of
// the frame. A focal point works for any frame shape, so a position set in the
// studio carries over to the wide desktop banner, a tall phone frame and the
// narrow gallery slats alike. Older photos store x/y instead (offset of the
// image centre from the frame centre, in % of the frame, the Design tool's
// model); those are converted per frame in `placement`.
//
// `crop` ({x, y, w, h}, fractions of the original image) cuts the photo down
// before anything else happens: everywhere the photo appears, it behaves as if
// the cropped part were the whole upload, so zoom and focal point are relative
// to the crop, and the gallery frames a piece at the crop's shape.
//
// Lookup order for a slot: Danique's upload (ad-photos) → the photo that was
// dropped into the Design file (defaultPhotos.json, generated by
// `npm run import-photos`) → the slot's built-in src → empty placeholder.

export const PhotosContext = createContext({});

// Gallery and testimonial photos are cropped before upload, so a crop saved
// there earlier is ignored and the whole photo shows.
const NO_CROP = /^ad-(gal|t)-|^ad-t\d/;

export function resolvePhoto(photos, slotId, fallbackSrc, fallbackFocus) {
  const own = photos && photos[slotId];
  const strip = (p) => (NO_CROP.test(slotId) ? { ...p, crop: undefined } : p);
  if (own && own.url) return normalizePhoto(strip(own));
  const def = DEFAULT_PHOTOS[slotId];
  if (def && def.url) return normalizePhoto(strip(def));
  if (fallbackSrc) return normalizePhoto({ url: fallbackSrc, ...fallbackFocus });
  return null;
}

export function usePhoto(slotId, fallbackSrc, fallbackFocus) {
  return resolvePhoto(useContext(PhotosContext), slotId, fallbackSrc, fallbackFocus);
}

const clamp01 = (v) => Math.min(1, Math.max(0, v));

export function normalizePhoto(p) {
  const n = (v, d) => (Number.isFinite(v) ? v : d);
  const out = { url: p.url, s: Math.min(4, Math.max(1, n(p.s, 1))) };
  if (Number.isFinite(p.fx) || Number.isFinite(p.fy)) {
    out.fx = clamp01(n(p.fx, 0.5));
    out.fy = clamp01(n(p.fy, 0.5));
  } else {
    out.x = n(p.x, 0);
    out.y = n(p.y, 0);
  }
  const c = p.crop;
  if (c && [c.x, c.y, c.w, c.h].every(Number.isFinite)) {
    const x = clamp01(c.x);
    const y = clamp01(c.y);
    const w = Math.min(c.w, 1 - x);
    const h = Math.min(c.h, 1 - y);
    if (w >= 0.02 && h >= 0.02) out.crop = { x, y, w, h };
  }
  return out;
}

// The shape (w/h) a photo shows at, after its crop, from the upload's own shape.
export function croppedRatio(photo, naturalRatio) {
  const c = photo && photo.crop;
  return c ? naturalRatio * (c.w / c.h) : naturalRatio;
}

// Where the <img> goes in this frame, in frame-%, with the crop applied: the
// cropped part is placed like a whole photo, then the full image is sized and
// shifted so exactly that part lands there.
export function imageBox(photo, naturalRatio, frameRatio) {
  const box = placement(photo, croppedRatio(photo, naturalRatio), frameRatio);
  const c = photo.crop;
  if (!c) return box;
  const w = box.w / c.w;
  const h = box.h / c.h;
  return { w, h, left: box.left - c.x * w, top: box.top - c.y * h };
}

// True when the photo is a plain centred cover-fill (no layout maths needed).
export function isPlain(photo) {
  if (photo.crop || photo.s !== 1) return false;
  if ('fx' in photo) return photo.fx === 0.5 && photo.fy === 0.5;
  return !photo.x && !photo.y;
}

// Image size in frame-% for a given image ratio (w/h) and frame ratio (w/h).
export function photoBox(s, imageRatio, frameRatio) {
  return {
    w: s * 100 * Math.max(1, imageRatio / frameRatio),
    h: s * 100 * Math.max(1, frameRatio / imageRatio),
  };
}

// The focal point of a photo for this frame (legacy x/y converted).
export function focusOf(photo, imageRatio, frameRatio) {
  if ('fx' in photo) return { fx: photo.fx, fy: photo.fy };
  const { w, h } = photoBox(photo.s, imageRatio, frameRatio);
  return { fx: clamp01(0.5 - photo.x / w), fy: clamp01(0.5 - photo.y / h) };
}

// Where the image goes in this frame: size and top-left corner in frame-%.
// The focal point is centred as far as possible without showing a gap.
export function placement(photo, imageRatio, frameRatio) {
  const { w, h } = photoBox(photo.s, imageRatio, frameRatio);
  const { fx, fy } = focusOf(photo, imageRatio, frameRatio);
  const left = Math.min(0, Math.max(100 - w, 50 - fx * w));
  const top = Math.min(0, Math.max(100 - h, 50 - fy * h));
  return { w, h, left, top };
}
