import { createContext, useContext } from 'react';
import DEFAULT_PHOTOS from './defaultPhotos.json';

// A photo is {url, s, x, y}: s = zoom (1 = cover-fill), x/y = offset of the
// image centre from the frame centre, in % of the frame. Same model as the
// Design tool's image-slot, so crops made there carry over.
//
// Lookup order for a slot: Danique's upload (ad-photos) → the photo that was
// dropped into the Design file (defaultPhotos.json, generated by
// `npm run import-photos`) → the slot's built-in src → empty placeholder.

export const PhotosContext = createContext({});

export function resolvePhoto(photos, slotId, fallbackSrc) {
  const own = photos && photos[slotId];
  if (own && own.url) return normalizePhoto(own);
  const def = DEFAULT_PHOTOS[slotId];
  if (def && def.url) return normalizePhoto(def);
  if (fallbackSrc) return { url: fallbackSrc, s: 1, x: 0, y: 0 };
  return null;
}

export function usePhoto(slotId, fallbackSrc) {
  return resolvePhoto(useContext(PhotosContext), slotId, fallbackSrc);
}

export function normalizePhoto(p) {
  const n = (v, d) => (Number.isFinite(v) ? v : d);
  return { url: p.url, s: Math.min(4, Math.max(1, n(p.s, 1))), x: n(p.x, 0), y: n(p.y, 0) };
}

// Image box in frame-% for a given image ratio (w/h) and frame ratio (w/h).
export function photoBox(photo, imageRatio, frameRatio) {
  const w = photo.s * 100 * Math.max(1, imageRatio / frameRatio);
  const h = photo.s * 100 * Math.max(1, frameRatio / imageRatio);
  return { w, h, maxX: Math.max(0, (w - 100) / 2), maxY: Math.max(0, (h - 100) / 2) };
}
