// Commission page text, ported from Commission.dc.html. The form now hands the
// answers to WhatsApp instead of uploading, so the copy says so.
// msg* strings build the WhatsApp message; waPrefill is the "talk first" link.

export const STRINGS = {
  en: {
    back: 'Back to the website',
    eyebrow: 'Start your commission', title1: 'Tell me about', title2: 'your moment.',
    intro: "A few questions and the size you'd like, then you'll send me your photo on WhatsApp. Artworks are made in A5 and A4. I'll confirm the price with you before anything is started.",
    secureT: 'Secure & private', secureB: 'Your photos are only used for your artwork.',
    fastT: 'Fast response', fastB: 'Usually within the same day.',
    studioT: 'Studio', studioB: "'s-Hertogenbosch, the Netherlands",
    talkFirst: 'Prefer to talk it through first?',
    waPrefill: 'Hi Danique!',
    thanks: 'Almost there.',
    thanksB1: 'WhatsApp has opened with your answers.',
    thanksB2: 'Press send and attach your photo there.',
    thanksRetry: "WhatsApp didn't open?", thanksRetryLink: 'Tap here',
    fName: 'Your name', fContact: 'Email or phone', fPhoto: 'Your photo',
    fPhotoNote: "You'll attach your photo in WhatsApp, right after you press the button below.",
    fPhotoHint: 'JPG, PNG or HEIC. The highest resolution you have is best.',
    fWhat: 'Where is this, and what is it?',
    fWhy: 'Why is this moment meaningful to you?',
    fFeel: 'How does it make you feel when you think of it?',
    fSize: 'Size', fExtra: 'Anything else I should know?',
    fSubmit: 'Continue on WhatsApp', fNoPay: "No payment now. I'll confirm the price first.",
    msgHello: "Hi Danique, I'd like to commission an artwork.",
    msgName: 'Name', msgSize: 'Size',
    msgClose: "I'll send my photo in this chat.",
    footCopy: "© 2026 Atelier Danique · 's-Hertogenbosch"
  },
  pt: {
    back: 'Voltar ao site',
    eyebrow: 'Comece sua encomenda', title1: 'Conte-me sobre', title2: 'o seu momento.',
    intro: 'Algumas perguntas e o tamanho que você prefere, depois você me manda sua foto pelo WhatsApp. As obras são feitas em A5 e A4. Confirmo o preço com você antes de começar qualquer coisa.',
    secureT: 'Seguro e privado', secureB: 'Suas fotos são usadas apenas para a sua obra.',
    fastT: 'Resposta rápida', fastB: 'Normalmente no mesmo dia.',
    studioT: 'Ateliê', studioB: "'s-Hertogenbosch, Holanda",
    talkFirst: 'Prefere conversar antes?',
    waPrefill: 'Oi Danique!',
    thanks: 'Quase lá.',
    thanksB1: 'O WhatsApp abriu com as suas respostas.',
    thanksB2: 'É só enviar a mensagem e anexar sua foto por lá.',
    thanksRetry: 'O WhatsApp não abriu?', thanksRetryLink: 'Toque aqui',
    fName: 'Seu nome', fContact: 'E-mail ou telefone', fPhoto: 'Sua foto',
    fPhotoNote: 'Você anexa sua foto no WhatsApp, logo depois de tocar no botão abaixo.',
    fPhotoHint: 'JPG, PNG ou HEIC. Quanto maior a resolução, melhor.',
    fWhat: 'Onde é isso e o que é?',
    fWhy: 'Por que esse momento é especial para você?',
    fFeel: 'O que você sente quando pensa nele?',
    fSize: 'Tamanho', fExtra: 'Mais alguma coisa que eu deva saber?',
    fSubmit: 'Continuar no WhatsApp', fNoPay: 'Sem pagamento agora. Confirmo o preço primeiro.',
    msgHello: 'Oi Danique, gostaria de encomendar uma obra.',
    msgName: 'Nome', msgSize: 'Tamanho',
    msgClose: 'Vou mandar minha foto aqui nesta conversa.',
    footCopy: "© 2026 Atelier Danique · 's-Hertogenbosch"
  },
  nl: {
    back: 'Terug naar de website',
    eyebrow: 'Start je opdracht', title1: 'Vertel me over', title2: 'jouw moment.',
    intro: 'Een paar vragen en het formaat dat je wilt, daarna stuur je me je foto via WhatsApp. Werken worden gemaakt in A5 en A4. Ik bevestig de prijs met je voordat er iets begint.',
    secureT: 'Veilig & privé', secureB: "Je foto's worden alleen voor jouw werk gebruikt.",
    fastT: 'Snel antwoord', fastB: 'Meestal dezelfde dag.',
    studioT: 'Atelier', studioB: "'s-Hertogenbosch, Nederland",
    talkFirst: 'Liever eerst even overleggen?',
    waPrefill: 'Hoi Danique!',
    thanks: 'Bijna klaar.',
    thanksB1: 'WhatsApp is geopend met je antwoorden.',
    thanksB2: 'Druk op verzenden en voeg daar je foto toe.',
    thanksRetry: 'Ging WhatsApp niet open?', thanksRetryLink: 'Tik hier',
    fName: 'Je naam', fContact: 'E-mail of telefoon', fPhoto: 'Je foto',
    fPhotoNote: 'Je voegt je foto toe in WhatsApp, meteen nadat je op de knop hieronder drukt.',
    fPhotoHint: 'JPG, PNG of HEIC. De hoogste resolutie die je hebt is het beste.',
    fWhat: 'Waar is dit, en wat is het?',
    fWhy: 'Waarom is dit moment belangrijk voor je?',
    fFeel: 'Wat voel je als je eraan denkt?',
    fSize: 'Formaat', fExtra: 'Is er nog iets dat ik moet weten?',
    fSubmit: 'Verder op WhatsApp', fNoPay: 'Nu nog geen betaling. Ik bevestig eerst de prijs.',
    msgHello: 'Hoi Danique, ik wil graag een kunstwerk laten maken.',
    msgName: 'Naam', msgSize: 'Formaat',
    msgClose: 'Ik stuur mijn foto in deze chat.',
    footCopy: "© 2026 Atelier Danique · 's-Hertogenbosch"
  }
};
