// Commission page text, ported from Commission.dc.html. The form sends the
// answers by email (with the photo) or hands them to WhatsApp.
// msg* strings build the WhatsApp message; waPrefill is the "talk first" link.

export const STRINGS = {
  en: {
    back: 'Back to the website',
    eyebrow: 'Start your commission', title1: 'Tell me about', title2: 'your moment.',
    intro: "A few questions and the size you'd like, then send it to me by email or on WhatsApp. Artworks are made in A5, A4 and A3. I'll confirm the price with you before anything is started.",
    secureT: 'Secure & private', secureB: 'Your photos are only used for your artwork.',
    fastT: 'Fast response', fastB: 'Usually within the same day.',
    studioT: 'Studio', studioB: "'s-Hertogenbosch, the Netherlands",
    talkFirst: 'Prefer to talk it through first?',
    waPrefill: 'Hi Danique!',
    thanks: 'Almost there.',
    thanksB1: 'WhatsApp has opened with your answers.',
    thanksB2: 'Press send and attach your photo there.',
    thanksRetry: "WhatsApp didn't open?", thanksRetryLink: 'Tap here',
    fPhotoPick: 'Choose a photo', fPhotoChange: 'Choose another photo', fPhotoRemove: 'Remove',
    fSubmitEmail: 'Send by email', fSending: 'Sending…',
    mailThanks: 'Thank you!', mailThanksB1: 'Your answers have reached me.', mailThanksB2: "I'll get back to you soon, usually the same day.",
    mailThanksNoPhoto: 'You can send me your photo when I reply.',
    errSend: 'Something went wrong. Please try again, or send it on WhatsApp.',
    errTooLarge: 'This photo is too large to send. Try a JPG, or send it on WhatsApp.',
    fName: 'Your name', fContact: 'Email', fPhoto: 'Your photo',
    fPhotoNote: 'Sending by email? Add your photo here. On WhatsApp you attach it in the chat instead.',
    fWhat: 'Where is this, and what is it?',
    fWhy: 'Why is this moment meaningful to you?',
    fFeel: 'How does it make you feel when you think of it?',
    fSize: 'Size', fExtra: 'Anything else I should know?',
    fSubmit: 'Send on WhatsApp', fNoPay: "No payment now. I'll confirm the price first.",
    msgHello: "Hi Danique, I'd like to commission an artwork.",
    msgName: 'Name', msgSize: 'Size',
    msgClose: "I'll send my photo in this chat.",
    footCopy: "© 2026 Atelier Danique · 's-Hertogenbosch"
  },
  pt: {
    back: 'Voltar ao site',
    eyebrow: 'Comece sua encomenda', title1: 'Conte-me sobre', title2: 'o seu momento.',
    intro: 'Algumas perguntas e o tamanho que você prefere, depois é só me enviar por e-mail ou pelo WhatsApp. As obras são feitas em A5, A4 e A3. Confirmo o preço com você antes de começar qualquer coisa.',
    secureT: 'Seguro e privado', secureB: 'Suas fotos são usadas apenas para a sua obra.',
    fastT: 'Resposta rápida', fastB: 'Normalmente no mesmo dia.',
    studioT: 'Ateliê', studioB: "'s-Hertogenbosch, Holanda",
    talkFirst: 'Prefere conversar antes?',
    waPrefill: 'Oi Danique!',
    thanks: 'Quase lá.',
    thanksB1: 'O WhatsApp abriu com as suas respostas.',
    thanksB2: 'É só enviar a mensagem e anexar sua foto por lá.',
    thanksRetry: 'O WhatsApp não abriu?', thanksRetryLink: 'Toque aqui',
    fPhotoPick: 'Escolher uma foto', fPhotoChange: 'Escolher outra foto', fPhotoRemove: 'Remover',
    fSubmitEmail: 'Enviar por e-mail', fSending: 'Enviando…',
    mailThanks: 'Obrigada!', mailThanksB1: 'Suas respostas chegaram até mim.', mailThanksB2: 'Respondo em breve, normalmente no mesmo dia.',
    mailThanksNoPhoto: 'Você pode me mandar sua foto quando eu responder.',
    errSend: 'Algo deu errado. Tente novamente ou envie pelo WhatsApp.',
    errTooLarge: 'Esta foto é grande demais para enviar. Tente um JPG ou envie pelo WhatsApp.',
    fName: 'Seu nome', fContact: 'E-mail', fPhoto: 'Sua foto',
    fPhotoNote: 'Vai enviar por e-mail? Adicione sua foto aqui. No WhatsApp, você anexa a foto na conversa.',
    fWhat: 'Onde é isso e o que é?',
    fWhy: 'Por que esse momento é especial para você?',
    fFeel: 'O que você sente quando pensa nele?',
    fSize: 'Tamanho', fExtra: 'Mais alguma coisa que eu deva saber?',
    fSubmit: 'Enviar pelo WhatsApp', fNoPay: 'Sem pagamento agora. Confirmo o preço primeiro.',
    msgHello: 'Oi Danique, gostaria de encomendar uma obra.',
    msgName: 'Nome', msgSize: 'Tamanho',
    msgClose: 'Vou mandar minha foto aqui nesta conversa.',
    footCopy: "© 2026 Atelier Danique · 's-Hertogenbosch"
  },
  nl: {
    back: 'Terug naar de website',
    eyebrow: 'Start je opdracht', title1: 'Vertel me over', title2: 'jouw moment.',
    intro: 'Een paar vragen en het formaat dat je wilt, daarna stuur je het me per e-mail of via WhatsApp. Werken worden gemaakt in A5, A4 en A3. Ik bevestig de prijs met je voordat er iets begint.',
    secureT: 'Veilig & privé', secureB: "Je foto's worden alleen voor jouw werk gebruikt.",
    fastT: 'Snel antwoord', fastB: 'Meestal dezelfde dag.',
    studioT: 'Atelier', studioB: "'s-Hertogenbosch, Nederland",
    talkFirst: 'Liever eerst even overleggen?',
    waPrefill: 'Hoi Danique!',
    thanks: 'Bijna klaar.',
    thanksB1: 'WhatsApp is geopend met je antwoorden.',
    thanksB2: 'Druk op verzenden en voeg daar je foto toe.',
    thanksRetry: 'Ging WhatsApp niet open?', thanksRetryLink: 'Tik hier',
    fPhotoPick: 'Kies een foto', fPhotoChange: 'Kies een andere foto', fPhotoRemove: 'Verwijderen',
    fSubmitEmail: 'Versturen per e-mail', fSending: 'Bezig met versturen…',
    mailThanks: 'Dankjewel!', mailThanksB1: 'Je antwoorden zijn bij me aangekomen.', mailThanksB2: 'Ik laat snel van me horen, meestal dezelfde dag.',
    mailThanksNoPhoto: 'Je kunt je foto sturen als ik je antwoord.',
    errSend: 'Er ging iets mis. Probeer het opnieuw, of stuur het via WhatsApp.',
    errTooLarge: 'Deze foto is te groot om te versturen. Probeer een JPG, of stuur hem via WhatsApp.',
    fName: 'Je naam', fContact: 'E-mail', fPhoto: 'Je foto',
    fPhotoNote: 'Stuur je het per e-mail? Voeg hier je foto toe. Via WhatsApp voeg je hem in de chat toe.',
    fWhat: 'Waar is dit, en wat is het?',
    fWhy: 'Waarom is dit moment belangrijk voor je?',
    fFeel: 'Wat voel je als je eraan denkt?',
    fSize: 'Formaat', fExtra: 'Is er nog iets dat ik moet weten?',
    fSubmit: 'Versturen via WhatsApp', fNoPay: 'Nu nog geen betaling. Ik bevestig eerst de prijs.',
    msgHello: 'Hoi Danique, ik wil graag een kunstwerk laten maken.',
    msgName: 'Naam', msgSize: 'Formaat',
    msgClose: 'Ik stuur mijn foto in deze chat.',
    footCopy: "© 2026 Atelier Danique · 's-Hertogenbosch"
  }
};
